{%- if cookiecutter.use_pre_commit == 'y' %}
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    - id: isort
      args: ["--profile", "black"]
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
{%- endif %}